main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

menu/urls.py
from django.urls import path
from . import views

app_name = "menu"

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

menu/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def __float__(self):
        return self.price

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

main/views.py
from django.shortcuts import render

# from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza


# Create your views here.
def index(request):
    ''' pizzas = Pizza.objects.all()
    pizza_names_and_price = [pizza.name + " : " + str(pizza.price) + "$" for pizza in pizzas]
    pizzas_names_and_price_str = ", ".join(pizza_names_and_price)
    return HttpResponse("Our Menu : " + pizzas_names_and_price_str)'''

    pizzas = Pizza.objects.all().order_by('price')
    return render(request, 'menu/index.html', {'pizzas': pizzas})


def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by("price")
    json = serializers.serialize("json", pizzas)
    return HttpResponse(json)

main/templates/main/index.html
{% load static %}

<!--<!DOCTYPE html>-->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>MamaPizza</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}" />
  </head>
  <body>
  <div class="centered">
    <img id="small_logo" src="{% static 'main/images/main_logo.png' %}" alt="logo.png" />
    <a class="menu" href="{% url 'menu:index' %}">Check Our Menu</a>
  </div>



  </body>
</html>

menu/templates/menu/index.html
{% load static %}

<!--<!DOCTYPE html>-->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Pizza Menu</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}" />
  </head>
  <body>
  <a href="{% url 'main:index' %}"><img id="logo" src="{% static 'menu/images/small_logo.png' %}" alt="" /></a>

    <div class="title">
      <h1>The Pizza Menu</h1>
    </div>

    <div class="menu-item">
      {% for pizza in pizzas %}
      <div class="items">
        <span class="menu-list">{{pizza.name}}:</span>
        <span class="menu-price">{{pizza.price | floatformat:2}}$</span>

        <span class="menu-ingred">{{pizza.ingredients}}</span>

        {% if pizza.vegetarian %}
        <span class="menu-list-badge">VEGETARIAN</span>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </body>
</html>